class C4Question2 extends AbstractQuestion {
	constructor() {

		var commissions = [11, 11, 11, 12, 12, 12, 12, 13, 13, 13];
		var commissions2 = [3, 3, 3, 4, 4, 4, 4, 5, 5, 5];
		var salaries = [50000, 51000, 52000, 53000, 54000, 55000, 56000, 57000, 58000, 60000];

		super();

		this.variables = {
			commission: commissions[Math.floor(Math.random() * 10)],
			commission2: commissions2[Math.floor(Math.random() * 10)],
			salary: salaries[Math.floor(Math.random() * 10)]
		}

		this.inputDiv.setAttribute('id', 'QC4-1-inputDiv');
		this.inputDiv.remove();

		this.container.setAttribute('id', 'question-containerC4');
		this.question.innerHTML = `Tom, the VP of sales at Shyla Industries, is deciding 
		between hiring a manufacturers' rep versus hiring a full-time salesperson (i.e., a captive rep).  
		The manufacturers' rep would be paid a straight commission of ${this.variables.commission}% on dollar sales. 
		The full-time salesperson would cost an annual fee of $${Number(this.variables.salary).toLocaleString()} in base salary and benefits, 
		plus ${this.variables.commission2}% commission on dollar sales. <br> <br> Tom wants to go with the low-cost option, and 
		understands that cost depends on the level of sales generated by the new hire -- and he asked you to do the calculations: `;

		this.input.setAttribute('placeholder', "");
		this.paragraph = document.createElement('p');
		this.paragraph.className = "QC4-1-paragraph";
		this.paragraph.innerHTML = `You should tell Tom that a manufacturers' rep costs less as long as dollar sales is less than: `;
		this.container.appendChild(this.paragraph);
		this.paragraph.appendChild(this.inputDiv);


	}

	calcAnswer(c, c2, s) {
		return s/((c - c2)/ 100);
	}

	checkAnswer(){
		var answer = this.calcAnswer(this.variables.commission, this.variables.commission2, this.variables.salary);

		if (this.getValue() >= (answer - .05) && this.getValue() <= (answer + .05)) {
			this.input.style.color = 'white';
			this.input.style.backgroundColor = 'green';
			this.setValue((answer).toFixed(2));
		} else {
			this.input.style.color = 'white';
			this.input.style.backgroundColor = 'red';
			this.setValue((answer).toFixed(2));
		}
	}
}