class Question17 extends AbstractQuestionTwo {
	constructor() {

		var rsalaries = [60000,  60000,  60000,  80000,  80000,  75000,  75000,  75000,  65000,  65000];
		var psalaries = [200000, 300000, 250000, 250000, 250000, 200000, 200000, 250000, 300000, 200000];
		var ballAds =   [300000, 400000, 250000, 450000, 200000, 300000, 450000, 200000, 400000, 300000];
		var batAds =    [100000, 200000, 100000, 200000, 150000, 100000, 250000, 150000, 200000, 100000];
		var percents =  [70,     70,     70,     75,     75,     75,     75,     80,     80,     80];

		super();

		var index = Math.floor(Math.random() * 10);
		this.variables = {
			rsalary: rsalaries[index],
			psalary: psalaries[index],
			ballAd: ballAds[index],
			batAd: batAds[index],
			percent: percents[index]
		}

		this.value4 = 0;

		this.container.setAttribute('id', 'question-containerC15');
		this.explanation.setAttribute('id', 'Q17-paragraph1');
		this.explanation.innerHTML =`Balls 'n' Bats is a $24 million dollar company with 1 president 
		and 10 sales reps in these two territories: Northern U.S. ($16 million in sales, 7 reps), 
		Southern U.S. ($8 million in sales, 3 reps).`;
		this.explanation2 = document.createElement('div');
		this.explanation2.className = "Q17-paragraph2";
		this.explanation2.innerHTML = `The company sells two different products (and each rep sells both): <br>
		-Balls ($18 million in sales)<br>
		-Bats ($6 million in sales).`;
		this.container.appendChild(this.explanation2);
		this.explanation3 = document.createElement('div');
		this.explanation3.className = "Q17-paragraph3";
		this.explanation3.innerHTML = `And you can assume that the following list contains information on all costs for this company: `
		this.explanation4 = document.createElement('div');
		this.explanation4.className = "Q17-paragraph4";
		this.explanation4.innerHTML = `
				Each rep is paid a straight salary of $${Number(this.variables.rsalary).toLocaleString()} <br>
				The company president is paid a salary of $${Number(this.variables.psalary).toLocaleString()} <br>
				They recently ran a national TV ad for balls, which cost $${Number(this.variables.ballAd).toLocaleString()} <br>
				And they separately they ran a national TV ad for bats, which cost $${Number(this.variables.batAd).toLocaleString()} <br>
				Cost of goods sold is exactly ${this.variables.percent}% of sales`;
		this.explanation5 = document.createElement('div');
		this.explanation5.className = 'Q17-paragraph5';
		this.explanation5.innerHTML = '1)  Based on a full cost analysis that allocates indirect costs using % of sales';
		this.container.appendChild(this.explanation3);	
		this.container.appendChild(this.explanation4);
		this.container.appendChild(this.explanation5);

		this.questionDiv4 = document.createElement('div');
		this.questionDiv4.className = "question-div";
		this.questionDiv4.setAttribute('id', 'Q17-questionDiv');
		this.question4 = document.createElement('p');
		this.question4.className = "question-paragraph";
		this.input4 = document.createElement('input');
		this.input4.className = "answer-input";
		this.input4.type = "number";
		this.questionDiv4.appendChild(this.question4);
		this.questionDiv4.appendChild(this.input4);
		this.questionDivContainer.appendChild(this.questionDiv4);

		this.question1.innerHTML = `a. How much of the company profit is generated by the Southern U.S. territory?`;
		this.question2.innerHTML = `b. How much of the company profit is generated by the Northern U.S. territory?`;
		this.question3.innerHTML = `c. How much of the company profit is generated by bats?`;
		this.question4.innerHTML = `d. How much of the company profit is generated by balls?`;
		this.input1.setAttribute('placeholder', 'Answer in dollars');
		this.input2.setAttribute('placeholder', 'Answer in dollars');
		this.input3.setAttribute('placeholder', 'Answer in dollars');
		this.input4.setAttribute('placeholder', 'Answer in dollars');


	}

	calcAnswer(p, ps, rs, bat, ball) {
		var answer1, answer2, answer3, answer4;

		answer1 = (((100 - p)/100) * 8000000) - (rs * 3) - ((bat + ball + ps)/3);
		answer2 = (((100 - p)/100) * 16000000) - (rs * 7) - ((bat + ball + ps)/1.5);
		answer3 = (((100 - p)/100) * 6000000) - (bat) - (((rs*10) + ps) * .25);
		answer4 = (((100 - p)/100) * 18000000) - (ball) - (((rs*10) + ps) * .75);

		return [answer1, answer2, answer3, answer4];
	}

	checkAnswer() {
		var answers = this.calcAnswer(this.variables.percent, this.variables.psalary, 
			this.variables.rsalary, this.variables.batAd, this.variables.ballAd);

		if (this.getValue1() >= (answers[0] - .01) && this.getValue1() <= (answers[0] + .01)) {
			this.input1.style.color = 'white';
			this.input1.style.backgroundColor = 'green';
			this.setValue1(Math.round(answers[0]));
		} else {
			this.input1.style.color = 'white';
			this.input1.style.backgroundColor = 'red';
			this.setValue1(Math.round(answers[0]));
		}

		if (this.getValue2() >= (answers[1] - .01) && this.getValue2() <= (answers[1] + .01)) {
			this.input2.style.color = 'white';
			this.input2.style.backgroundColor = 'green';
			this.setValue2(Math.round(answers[1]));
		} else {
			this.input2.style.color = 'white';
			this.input2.style.backgroundColor = 'red';
			this.setValue2(Math.round(answers[1]));
		}

		if (this.getValue3() >= (answers[2] - .01) && this.getValue3() <= (answers[2] + .01)) {
			this.input3.style.color = 'white';
			this.input3.style.backgroundColor = 'green';
			this.setValue3(Math.round(answers[2]));
		} else {
			this.input3.style.color = 'white';
			this.input3.style.backgroundColor = 'red';
			this.setValue3(Math.round(answers[2]));
		}

		if (this.getValue4() >= (answers[3] - .01) && this.getValue4() <= (answers[3] + .01)) {
			this.input4.style.color = 'white';
			this.input4.style.backgroundColor = 'green';
			this.setValue4(Math.round(answers[3]));
		} else {
			this.input4.style.color = 'white';
			this.input4.style.backgroundColor = 'red';
			this.setValue4(Math.round(answers[3]));
		}

	}

	getValue4() {
		this.value4 = this.input4.value;
		return this.value4;
	}

	setValue4(val) {
		this.input4.value = val;
		this.value4 = this.input4.value;
	}
}